################################# Default configuration ###################
baseURL = "https://ngschoollocal.netlify.com"
title = "#NGSchool"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# disable language
disableLanguages = []


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/Ionicons/css/ionicons.min.css"
  [[params.plugins.css]]
  link = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  link = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  link = "plugins/font-awesome/font-awesome.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
 
  [[menu.main]]
  name = "News"
  URL = "post"
  weight = 2
 
  [[menu.main]]
  name = "Society"
  URL = "society"
  weight = 3
  
  [[menu.main]]
  weight = 4
  name = "NGSchool"
  hasChildren = true

    [[menu.main]]
    parent = "NGSchool"
    name = "2020"
    URL = "ngschool2020"
    weight = 1

    [[menu.main]]
    parent = "NGSchool"
    name = "2019"
    URL = "ngschool2019"
    weight = 2

    [[menu.main]]
    parent = "NGSchool"
    name = "2018"
    URL = "ngschool2018"
    weight = 3

    [[menu.main]]
    parent = "NGSchool"
    name = "2017"
    URL = "ngschool2017"
    weight = 4

    [[menu.main]]
    parent = "NGSchool"
    name = "2016"
    URL = "ngschool2016"
    weight = 5
    
  [[menu.main]]
  weight = 5
  name = "Conference 2020"
  URL = "conference"

  [[menu.main]]
  name = "People"
  URL = "people"
  weight = 6
  
  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 8

  
  # footer menu
  [[menu.footer]]
  name = "#NGSchool"
  URL = "/about"
  weight = 1
  
  
  [[menu.footer]]
  name = "Society"
  URL = "/society"
  weight = 2


  [[menu.footer]]
  name = "FAQ"
  URL = "/faq"
  weight = 3
  
  
  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "ngschool"
# Contact Information
# mobile = "0124857985320"
email = "info@ngschool.eu"
location = "ul. Lindleya 16, 02-013 Warsaw, Poland"
# contact form action
contact_form_action = "https://formspree.io/xrgkebrz" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "Your ID"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

  # Navigation get start button
  [params.nav_button]
  enable = true
  label = "Get A Quote"
  link = "contact"

  # google map
  [params.gmap]
  enable = true
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
  map_latitude = "52.226128"
  map_longitude = "20.996416"
  map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/NGSchool.eu/"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/NGSchoolEU"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/ngschooleu"

################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  # contentDir = "content/english"
  weight = 1
  home = "Home"
  # copyright
  copyright = "Copyright &copy; [#NGSchool](https://ngschool.eu) 2020 | Theme by [Themefisher](https://themefisher.com)"
