################################# Default configuration ###################
title = "NGSchool | Summer School in Bioinformatics"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# disable language
disableLanguages = ["pl"]


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "/plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "/plugins/Ionicons/css/ionicons.min.css"
  [[params.plugins.css]]
  link = "/plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  link = "/plugins/slick/slick.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "/plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "/plugins/popper/popper.min.js"
  [[params.plugins.js]]
  link = "/plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "/plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "/plugins/magnific-popup/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  link = "/plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  link = "/plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "News"
  URL = "post"
  weight = 1

  [[menu.main]]
  name = "About us"
  weight = 2
  hasChildren = true

    [[menu.main]]
    parent = "About us"
    name = "Our mission"
    URL = "about"
    weight = 3
  
    [[menu.main]]
    parent = "About us"
    name = "People"
    URL = "people"
    weight = 4

    [[menu.main]]
    parent = "About us"
    name = "Photos"
    URL = "galleries"
    weight = 5

  [[menu.main]]
  name = "Society"
  hasChildren = true
  weight = 3
  
    [[menu.main]]
    parent = "Society"
    name = "About"
    URL = "society"
    weight = 7

    [[menu.main]]
    parent = "Society"
    name = "Statute"
    URL = "statute"
    weight = 8

    [[menu.main]]
    parent = "Society"
    name = "Board"
    URL = "board"
    weight = 9

    [[menu.main]]
    parent = "Society"
    name = "Bank account"
    URL = "bank_account"
    weight = 10

  [[menu.main]]
  name = "NGSchool2025"
  URL = "ngschool2025"
  weight = 4

  [[menu.main]]
  name = "Other projects"
  weight = 5
  hasChildren = true
  
    [[menu.main]]
    parent = "Other projects"
    name = "NGSchool"
    weight = 1
    hasChildren = true
      
      [[menu.main]]
      parent = "NGSchool"
      name = "2023"
      URL = "ngschool2023"
      weight = 1

      [[menu.main]]
      parent = "NGSchool"
      name = "2022"
      URL = "ngschool2022"
      weight = 2

      [[menu.main]]
      parent = "NGSchool"
      name = "2019"
      URL = "ngschool2019"
      weight = 3

      [[menu.main]]
      parent = "NGSchool"
      name = "2018"
      URL = "ngschool2018"
      weight = 4

      [[menu.main]]
      parent = "NGSchool"
      name = "2017"
      URL = "ngschool2017"
      weight = 5

      [[menu.main]]
      parent = "NGSchool"
      name = "2016"
      URL = "ngschool2016"
      weight = 6

    [[menu.main]]
    parent = "Other projects"
    name = "NGSymposium"
    hasChildren = true
    weight = 2
   
      [[menu.main]]
      parent = "NGSymposium"
      name = "NGSymposium2022"
      URL = "ngsymposium2022"
      weight = 1

      [[menu.main]]
      parent = "NGSymposium"
      name = "Virtual 2020"
      URL = "virtual_ngsymposium2020"
      weight = 2

    [[menu.main]]
    parent = "Other projects"
    name = "NGSeminars"
    hasChildren = true
    weight = 3

      [[menu.main]]
      parent = "NGSeminars"
      name = "2021"
      URL = "ngseminars2021"
      weight = 1

      [[menu.main]]
      parent = "NGSeminars"
      name = "2020"
      URL = "ngseminars2020"
      weight = 2

    [[menu.main]]
    parent = "Other projects"
    name = "NGSprint"
    URL = "ngsprint"
    weight = 4

  [[menu.main]]
  name = "Donate"
  URL = "bank_account"
  weight = 6

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 8


  # footer menu
  [[menu.footer]]
  name = "NGSchool"
  URL = "/about"
  weight = 1

  [[menu.footer]]
  name = "Society"
  URL = "/society"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "/faq"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  weight = 4

  [[menu.footer]]
  name = "Privacy"
  URL = "/gdpr_policy"
  weight = 5

#################### default parameters ################################
[params]
logo = "/images/ngschool-logo.svg"
home = "Home"

# Meta data
description = "NGSchool (Next Generation School) is a platform to share the expertise in the field of Next Generation Sequencing Data Analysis and general Bioinformatics."
author = "NGSchool"

# Contact Information
email = "info@ngschool.eu"
location = "ul. Lindleya 16, 02-013 Warsaw, Poland"

# Legal info
president = "Karolina Sienkiewicz"
vice = "Diana Sharysh"
nip = "7010892593"
krs = "0000757658"
regon = "381825521"

# Account 2 (Wise)
account_bank = "Wise"
account_name = "Stowarzyszenie NGSchool / NGSchool Society"
account_swift = "TRWIBEB1XXX"
account_eur = "BE43 9670 2250 7501"
account_pln = "62 1020 1026 3741 0000 0000 3246"

# Account 1 (BNP Paribas)
account_bank_1 = "BNP Paribas"
account_name_1 = "Stowarzyszenie NGSchool / NGSchool Society"
account_swift_1 = "PPABPLPKXXX"
account_eur_1 = "69 1600 1462 1737 0687 8000 0003"
account_pln_1 = "26 1600 1462 1737 0687 8000 0001"

# contact form action
contact_form_action = "https://formspree.io/xrgkebrz" # contact form works with : https://formspree.io

# Google Analitycs
google_analitycs_id = "UA-159044812-1"

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

  # Navigation get start button
  [params.nav_button]
  enable = true
  label = "Get A Quote"
  link = "contact"

  # google map
  [params.gmap]
  enable = true
  #https://maps.googleapis.com/maps/api/js?key=AIzaSyB1TE8TSFkaS6dHA0Nzfnq9KvmxaEQ0Hx0&libraries=places
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyB1TE8TSFkaS6dHA0Nzfnq9KvmxaEQ0Hx0&libraries=places"
  map_latitude = "52.226128"
  map_longitude = "20.996416"
  map_marker = "/images/marker.png"


############################# social media ########################
[[params.social]]
name = "Facebook"
icon = "fab fa-facebook-f fa-2x"
link = "https://www.facebook.com/NGSchool.eu/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter fa-2x"
link = "https://twitter.com/NGSchoolEU"

[[params.social]]
name = "Instagram"
icon = "fab fa-instagram fa-2x"
link = "https://www.instagram.com/ngschooleu"

[[params.social]]
name = "YouTube"
icon = "fab fa-youtube fa-2x"
link = "https://www.youtube.com/NGSchoolEU"

[[params.social]]
name = "Discord"
icon = "fab fa-discord fa-2x"
link = "https://discord.gg/MhNeqwR"

################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content"
  weight = 1
  home = "Home"
  # copyright
  copyright = "Made & maintained by Szymon and Ula, Copyright &copy; [NGSchool](https://ngschool.eu) 2020-2024 | Theme by [Themefisher](https://themefisher.com)"
 
  ################################ Polish Language ########################
  [Languages.pl]
  languageName = "Pl"
  languageCode = "pl"
  contentDir = "content/polish"
  weight = 2
  home = "Home"
  # copyright
  copyright = "Strona stworzona i utrzymywana przez Szymona i Ulę, Copyright &copy; [NGSchool](https://ngschool.eu) 2020-2023 | Theme by [Themefisher](https://themefisher.com)"
	
	  # main menu
	  [[Languages.pl.menu.main]]
	  name = "About"
	  URL = "about"
	  weight = 1

	  [[Languages.pl.menu.main]]
	  name = "Society"
	  URL = "society"
	  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
