################################# Default configuration ###################
title = "#NGSchool"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# disable language
disableLanguages = ["pl"]


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "/plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "/plugins/Ionicons/css/ionicons.min.css"
  [[params.plugins.css]]
  link = "/plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  link = "/plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "/plugins/font-awesome/css/all.min.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "/plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "/plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "/plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "/plugins/magnific-popup/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  link = "/plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  link = "/plugins/google-map/gmap.js"
  [[params.plugins.js]]
  link = "/plugins/font-awesome/js/all.min.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Society"
  URL = "society"
  weight = 2

  [[menu.main]]
  name = "NGSchool"
  weight = 3
  hasChildren = true

    [[menu.main]]
    parent = "NGSchool"
    name = "2020"
    URL = "ngschool2020"
    weight = 1

    [[menu.main]]
    parent = "NGSchool"
    name = "2019"
    URL = "ngschool2019"
    weight = 2

    [[menu.main]]
    parent = "NGSchool"
    name = "2018"
    URL = "ngschool2018"
    weight = 3

    [[menu.main]]
    parent = "NGSchool"
    name = "2017"
    URL = "ngschool2017"
    weight = 4

    [[menu.main]]
    parent = "NGSchool"
    name = "2016"
    URL = "ngschool2016"
    weight = 5

  [[menu.main]]
  name = "Conference 2020"
  URL = "conference"
  weight = 4

  [[menu.main]]
  name = "People"
  URL = "people"
  weight = 5

  [[menu.main]]
  name = "Photos"
  URL = "galleries"
  weight = 6

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 7


  # footer menu
  [[menu.footer]]
  name = "#NGSchool"
  URL = "/about"
  weight = 1

  [[menu.footer]]
  name = "Society"
  URL = "/society"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "/faq"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  weight = 4

  [[menu.footer]]
  name = "Privacy"
  URL = "/gdpr_policy"
  weight = 5

#################### default parameters ################################
[params]
logo = "/images/logo.png"
home = "Home"
# Meta data
description = "#NGSchool (Next Generation School) is a platform to share the expertise in the field of Next Generation Sequencing Data Analysis and general Bioinformatics."
author = "ngschool"
# Contact Information
# mobile = "0124857985320"
email = "info@ngschool.eu"
location = "ul. Lindleya 16, 02-013 Warsaw, Poland"
president = "Katarzyna Kędzierska"
vice = "Lidia Lipińska"
nip = "7010892593"
krs = "0000757658"
regon = "381825521"
account_name = "Stowarzyszenie NGSchool / NGSchool Society"
account_swift = "BREXPLPWMBK"
account_pln = "PL67 1140 2004 0000 3102 7868 6219"
account_eur = "PL40 1140 2004 0000 3112 0774 0774"
# contact form action
contact_form_action = "https://formspree.io/xrgkebrz" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-159044812-1"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

  # Navigation get start button
  [params.nav_button]
  enable = true
  label = "Get A Quote"
  link = "contact"

  # google map
  [params.gmap]
  enable = true
  #https://maps.googleapis.com/maps/api/js?key=AIzaSyB1TE8TSFkaS6dHA0Nzfnq9KvmxaEQ0Hx0&libraries=places
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyB1TE8TSFkaS6dHA0Nzfnq9KvmxaEQ0Hx0&libraries=places"
  map_latitude = "52.226128"
  map_longitude = "20.996416"
  map_marker = "/images/marker.png"


############################# social site ########################
[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/NGSchool.eu/"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/NGSchoolEU"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/ngschooleu"

################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content"
  weight = 1
  home = "Home"
  # copyright
  copyright = "Copyright &copy; [#NGSchool](https://ngschool.eu) 2020 | Theme by [Themefisher](https://themefisher.com)"
 
  ################################ Poland Language ########################
  [Languages.pl]
  languageName = "Pl"
  languageCode = "pl"
  contentDir = "content/polish"
  weight = 2
  home = "Home"
  # copyright
  copyright = "Copyright &copy; [#NGSchool](https://ngschool.eu) 2020 | Theme by [Themefisher](https://themefisher.com)"
	
	  # main menu
	  [[Languages.pl.menu.main]]
	  name = "About"
	  URL = "about"
	  weight = 1

	  [[Languages.pl.menu.main]]
	  name = "Society"
	  URL = "society"
	  weight = 2
